### ISSUE TITLE
README Tutorial issue: stack build error

### ISSUE THREAD

**Issue by RyanFleck** [smucclaw/complaw#1]
Using Debian 9 within Windows Subsystem for Linux, attempting to follow the commands in the README instructions results in the following error. Is there an easy & obvious fix for this? Seems like one of the repository dependencies is inaccessible.

It's possible that this is a network/depencency/operating system issue within my local environment.
```
stack build
Downloading lts-15.12 build plan ...RedownloadFailed Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/fpco/lts-haskell/master//lts-15.12.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = Just (-3425)
  requestVersion       = HTTP/1.1
}
 "/home/rflec028/.stack/build-plan/lts-15.12.yaml" (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Connection","keep-alive"),("Content-Length","14"),("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; sandbox"),("Strict-Transport-Security","max-age=31536000"),("X-Content-Type-Options","nosniff"),("X-Frame-Options","deny"),("X-XSS-Protection","1; mode=block"),("Content-Type","text/plain; charset=utf-8"),("Via","1.1 varnish (Varnish/6.0)"),("X-GitHub-Request-Id","FAE2:2BF7:1831F:1BFF6:5ED7DDF1"),("Accept-Ranges","bytes"),("Date","Wed, 03 Jun 2020 17:29:22 GMT"),("Via","1.1 varnish"),("X-Served-By","cache-yyz4540-YYZ"),("X-Cache","MISS, MISS"),("X-Cache-Hits","0, 0"),("X-Timer","S1591205362.001724,VS0,VE95"),("Vary","Authorization,Accept-Encoding"),("Access-Control-Allow-Origin","*"),("X-Fastly-Request-ID","9f1b340ab4b9272a012521168fb1a9f1d60454bc"),("Expires","Wed, 03 Jun 2020 17:34:22 GMT"),("Source-Age","0")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose})
```

**Comment by mengwong** [comment]
You know, I was just complaining about this the other day … hoping to save
time and stand on the shoulders of giants, we outsource huge chunks of
infrastructure to package managers, UI frameworks, and third-party
libraries … and when the giants stumble and we have to roll up our sleeves
to work on a third-party codebase, we have to ask ourselves: how much time
are we really saving?

As Joel wrote nearly 20 years ago:
https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/

> Ten years ago, we might have imagined that new programming paradigms
would have made programming easier by now. Indeed, the abstractions we’ve
created over the years do allow us to deal with new orders of complexity in
software development that we didn’t have to deal with ten or fifteen years
ago, like GUI programming and network programming. And while these great
tools, like modern OO forms-based languages, let us get a lot of work done
incredibly quickly, suddenly one day we need to figure out a problem where
the abstraction leaked, and it takes 2 weeks. And when you need to hire a
programmer to do mostly VB programming, it’s not good enough to hire a VB
programmer, because they will get completely stuck in tar every time the VB
abstraction leaks.
> The Law of Leaky Abstractions is dragging us down.

**Comment by mengwong** [comment]
I might try using ghcjs to build a JS executable… if that works it could be
the first step toward a JS native implementation.

**Comment by mengwong** [comment]
ah, `stack upgrade` fixes this.
